set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN U9 [get_ports x]
set_property IOSTANDARD LVCMOS33 [get_ports x]
set_property PACKAGE_PIN U8 [get_ports t]					
set_property IOSTANDARD LVCMOS33 [get_ports t]
set_property PACKAGE_PIN T8 [get_ports y]
set_property IOSTANDARD LVCMOS33 [get_ports y]